Repository OdyOdyOdyOdy/ody-flutter, pull requests merged in 2025-02, with the labels that each got.

#51 feat: (Data, Domain, Presentation) Layer 구현
  ody_flutter/.gitignore
  ody_flutter/analysis_options.yaml
  ody_flutter/lib/config/routes.dart
  ody_flutter/lib/data/entity/gathering/gathering_request.dart
  ody_flutter/lib/data/entity/gathering/gathering_response.dart
  ody_flutter/lib/data/entity/mapper/gathering_mapper.dart
  ody_flutter/lib/data/network/base/base_exception.dart
  ody_flutter/lib/data/network/base/base_service.dart
  ody_flutter/lib/data/network/service/gathering_service_impl.dart
  ody_flutter/lib/data/repository/gathering_repository_impl.dart
  ody_flutter/lib/domain/model/gathering.dart
  ody_flutter/lib/domain/repository/gathering_repository.dart
  ody_flutter/lib/main.dart
  ody_flutter/lib/screens/gathering_creator_screen.dart
  ody_flutter/lib/screens/gatherings/gathering_creator_screen.dart
  ody_flutter/lib/screens/gatherings/gathering_creator_view_model.dart
  ody_flutter/pubspec.yaml
Labels: FEAT

#52 design: GatheringDetailScreen 디자인
  ody_flutter/assets/images/ic_big_cancel.svg
  ody_flutter/assets/images/ic_exit.svg
  ody_flutter/assets/images/ic_information.svg
  ody_flutter/lib/assets/fonts/pretendard_fonts.dart
  ody_flutter/lib/assets/images/images.dart
  ody_flutter/lib/config/routes.dart
  ody_flutter/lib/screens/gathering_detail/gathering_detail_screen.dart
  ody_flutter/lib/screens/gathering_detail/model/gathering_detail.dart
  ody_flutter/lib/screens/gathering_detail/model/mate.dart
  ody_flutter/lib/screens/gathering_detail_screen.dart
Labels: DESIGN

#55 bug: ci run test에서 .env 파일 못찾는 버그 수정
  .github/workflows/flutter_ci.yml
  ody_flutter/analysis_options.yaml
  ody_flutter/pubspec.yaml
Labels: BUG

#53 design: EtaBoardScreen 디자인
  ody_flutter/analysis_options.yaml
  ody_flutter/assets/images/ic_question_mark.svg
  ody_flutter/lib/assets/colors/colors.dart
  ody_flutter/lib/assets/images/images.dart
  ody_flutter/lib/config/routes.dart
  ody_flutter/lib/screens/eta_board/eta_board_screen.dart
  ody_flutter/lib/screens/eta_board/model/eta_status.dart
  ody_flutter/lib/screens/eta_board/model/mate_eta.dart
  ody_flutter/lib/screens/eta_board_screen.dart
Labels: DESIGN
